name: Java Deployment with Maven
run-name: CI/CD Implementation using Github Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  

      - name: Compile Java project with Maven
        run: mvn clean install

      - name: Get Jenkins Crumb Token
        id: crumb
        run: |
          export CRUMB=$(curl -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} https://8d5b-5-194-150-10.ngrok-free.app/crumbIssuer/api/json | jq -r '.crumb')
          echo "CRUMB=$CRUMB" >> $GITHUB_ENV

      - name: Trigger Jenkins Job to Deploy Java Application to Tomcat Server
        run: |
          curl -X POST "https://8d5b-5-194-150-10.ngrok-free.app/job/TomcatDeploymentDemo/build" \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
          -H "Jenkins-Crumb: ${{ env.CRUMB }}"
