name: Java Deployment with Maven
run-name: CI/CD Implementation using Github Actions

on:
  push:
    branches:
      - master
env:
  jenkins_job_name: ${{ vars.JENKINS_JOB }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  

      - name: Compile and Package Java project with Maven
        run: mvn clean install

      - name: Trigger Jenkins Job to Deploy Java Application to Tomcat Server
        run: |
          curl -X POST ${{ secrets.JENKINS_URL }}/job/$jenkins_job_name/build \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}
